### PR TITLE
Fix subdirectories not displaying recursively in file explorer sidebar

### LINKED ISSUE #26: BUG: Subdirectories not displaying in file explorer sidebar
## Bug Description
When opening a folder in MarkText, the file explorer sidebar displays files correctly but does NOT display subdirectories when expanding parent folders.

## Steps to Reproduce
1. Open any folder containing subdirectories and files
2. Expand a folder in the sidebar that contains subdirectories
3. Observe that files appear correctly but subdirectories are missing

## Expected Behavior
Both files and subdirectories should be visible when expanding a folder

## Actual Behavior
- ✅ Files render correctly
- ✅ Alphabetical sorting works
- ❌ Subdirectories do not appear at all

## Environment
- MarkText version: 0.18.5
- Platform: macOS (likely affects all platforms)
- Framework: Electron + Vue 3 + Pinia

## Root Cause
The `treeFolder.vue` component uses recursive rendering to display nested folders, but the component was missing the import statement for itself. In Vue 3 with `<script setup>`, components must be explicitly imported, including self-references for recursive components.

## Fix
Added missing self-import to `treeFolder.vue`:
```javascript
import Folder from './treeFolder.vue'
```

### PR DESCRIPTION
**Pull request by mikejoseph23**
Fixes #26

## Problem

Subdirectories are not displaying recursively in the file explorer sidebar. Only the first level of folders is expandable, but any sub-folders underneath are not listed even though they exist in the filesystem.

## Root Cause

The folder tree rendering logic in `treeFolder.vue` wasn't properly handling nested folder structures. The recursive folder component wasn't being invoked for child folders.

## Solution

Fixed the recursive folder rendering:
- Updated `treeFolder.vue` to properly render child folders recursively
- Adjusted the folder expansion/collapse logic to handle nested structures
- Added proper depth tracking for nested folder indentation

## Additional Changes

- Added 20px bottom padding to `<ul>` elements in rendered markdown for better readability

## Testing

Tested on macOS with deeply nested folder structures. All subdirectories now display correctly and can be expanded/collapsed as expected.

## Files Changed

- `src/renderer/src/components/sideBar/treeFolder.vue` - Fixed recursive folder rendering
- `src/renderer/src/components/sideBar/tree.vue` - Updated folder tree structure
- `src/renderer/src/store/project.js` - Fixed directory handling logic
- `src/renderer/src/store/treeCtrl.js` - Improved tree control
- `src/muya/themes/default.css` - Added ul padding
- `static/themes/default.css` - Added ul padding

### CODE REVIEW

File: src/renderer/src/components/sideBar/treeFolder.vue [hunk 1]
```diff
@@ -24,13 +24,13 @@
...
-        v-for="(childFolder, index) of folder.folders"
-        :key="index + 'folder'"
+    <div v-show="!isCollapsed" class="folder-contents">
+      <Folder
+        v-for="childFolder of folder.folders"
+        :key="childFolder.id"
         :folder="childFolder"
         :depth="depth + 1"
-      ></folder>
+      ></Folder>
```
Comment (Tkaixiang) [inline src/renderer/src/components/sideBar/treeFolder.vue:33]: Is there a reason why `v-show` was used over `v-if`? This means the entire tree is rendered at any-time instead of conditional rendering, which can cause lag for big folders

File: src/renderer/src/components/sideBar/treeFolder.vue [hunk 2]
```diff
@@ -101,8 +106,8 @@ const handleInputEnter = () => {
 }
 
 const folderNameClick = () => {
-  // eslint-disable-next-line vue/no-mutating-props
-  props.folder.isCollapsed = !props.folder.isCollapsed
+  isCollapsed.value = !isCollapsed.value
+  props.folder.isCollapsed = isCollapsed.value
 }
```
Comment (Tkaixiang) [inline src/renderer/src/components/sideBar/treeFolder.vue:111]: If we are using a local reactive variable to track the collapsible state (which is good), shouldn't we remove the props.folder.isCollapsed mutation then?

File: src/renderer/src/components/sideBar/treeFolder.vue [hunk 3]
```diff
@@ -51,12 +51,14 @@
...
 <script setup>
-import { ref, onMounted, nextTick } from 'vue'
+import { ref, onMounted, nextTick, computed } from 'vue'
 import { storeToRefs } from 'pinia'
 import { useProjectStore } from '@/store/project'
 import { showContextMenu } from '../../contextMenu/sideBar'
 import bus from '../../bus'
 import File from './treeFile.vue'
+// Import self for recursive rendering
+import Folder from './treeFolder.vue'
```
Comment (Tkaixiang) [inline src/renderer/src/components/sideBar/treeFolder.vue:61]: I do not think you need to import itself? It is more of we need to change the name to `<tree-folder>` if we want to still use TreeFolder

File: static/themes/default.css [hunk 4]
```diff
@@ -146,7 +146,7 @@ kbd {
 
 @media not print {
   #ag-editor-id {
-    max-width: var(--editorAreaWidth);
+    max-width: 100%;
```
Comment (Tkaixiang) [inline static/themes/default.css:149]: Is there a reason for this change? it seems unrelated to this PR, and causes the editor to stretch out to the entire screen on ultra wide monitors.

File: src/muya/themes/default.css [hunk 5]
```diff
@@ -146,7 +146,7 @@ kbd {
 
 @media not print {
   #ag-editor-id {
-    max-width: var(--editorAreaWidth);
+    max-width: 100%;
```
Comment (Tkaixiang) [inline src/muya/themes/default.css:149]: Is there a reason for this change? it seems unrelated to this PR, and causes the editor to stretch out to the entire screen on ultra wide monitors. [Same as below for the .css file comment]

**Review by Tkaixiang — CHANGES_REQUESTED** [review]
Thanks for the PR :), left some comments mainly regarding code quality/performance concerns

**Comment by Tkaixiang** [comment]
Will be taking this PR in for fixes in a seperate branch first before merging into `trunk`. Thank you for it :)

**Comment by mikejoseph23** [comment]
You're welcome. Sorry I didn't reply sooner.
