### PR TITLE
Fix: Prevent files from being marked as modified immediately on open

### LINKED ISSUE #31: Files marked as modified immediately upon opening (auto-normalization issue)
## Description

MarkText currently marks files as modified immediately upon opening them, even when no
user changes have been made. This causes unnecessary "unsaved changes" warnings when
switching tabs or closing files.

## Root Cause

The issue has two contributing factors:

1. **Automatic line ending normalization**: When `loadMarkdownFile()` detects CRLF line
endings or mixed line endings, it automatically converts them to LF and marks the file as
modified
2. **Muya editor content normalization**: When content is loaded into the Muya editor, it
performs internal normalization (whitespace adjustments, etc.) which triggers a content
change event

## Steps to Reproduce

1. Open a markdown file (especially one with CRLF line endings from Windows)
2. Don't make any changes
3. Try to close the tab or switch to another file
4. MarkText prompts "Do you want to save changes?" even though you made no edits

## Expected Behavior

Files should only be marked as modified when the user actually makes changes. Opening and
viewing a file should not trigger the unsaved changes indicator.

## Proposed Solution

Add a preference `autoNormalizeMarkdownOnOpen` (default: false) that:
- When disabled: Files are opened as-is, preserving original line endings until the user
makes actual changes
- When enabled: Maintains the old behavior for users who prefer automatic normalization

Additionally, ignore the first content change event from Muya after file load to prevent
false modification flags.

## Environment

- MarkText v0.18.5
- All platforms affected (macOS, Windows, Linux)

## Related

This improves user experience by eliminating a common UI annoyance where users are
constantly prompted about unsaved changes when they haven't modified anything.

### PR DESCRIPTION
**Pull request by mikejoseph23**
Fixes #31

## Problem

MarkText currently marks files as modified immediately upon opening them, even when no user changes have been made. This causes unnecessary "unsaved changes" warnings when switching tabs or closing files, creating a frustrating user experience.

### Root Cause

The issue has two contributing factors:

1. **Automatic line ending normalization on file open**: When `loadMarkdownFile()` detects CRLF line endings or mixed line endings, it automatically converts them to LF and sets `adjustLineEndingOnSave = true`. This marks the file as modified even though the user hasn't made any changes.

2. **Muya editor content normalization**: When content is loaded into the Muya editor via `setMarkdown()`, the editor performs its own internal normalization (whitespace adjustments, etc.). This triggers a `LISTEN_FOR_CONTENT_CHANGE` event that marks the file as unsaved, even when the file was just opened.

## Solution

This PR implements a two-part fix:

### 1. Optional Line Ending Normalization

Added a new preference `autoNormalizeMarkdownOnOpen` (default: `false`) that controls whether files should be automatically normalized when opened:

- **When disabled (default)**: Files are opened as-is with their original line endings. The editor still converts to LF internally (required by MarkText), but preserves the original format via `adjustLineEndingOnSave` flag. The file is only marked as modified when the user actually makes changes.
  
- **When enabled**: Maintains the old behavior where files with CRLF or mixed line endings are normalized immediately.

**Files modified**:
- `src/main/filesystem/markdown.js` - Added conditional normalization logic
- `src/main/preferences/schema.json` - Added preference definition  
- `src/renderer/src/prefComponents/editor/index.vue` - Added UI toggle
- `static/locales/en.json` - Added localization string
- `src/main/filesystem/watcher.js` - Propagated preference through file watching
- `src/main/windows/editor.js` - Passed preference to loadMarkdownFile

### 2. Ignore First Content Change from Muya

Added `isFirstContentChange` flag to the file state that ignores the first content change event after a file is loaded. This prevents Muya's internal normalization from marking files as unsaved.

**Files modified**:
- `src/renderer/src/store/help.js` - Added `isFirstContentChange: true` to `defaultFileState`
- `src/renderer/src/store/editor.js` - Modified `LISTEN_FOR_CONTENT_CHANGE` to skip first change

## Testing

Tested on macOS with files containing:
- CRLF line endings
- LF line endings  
- Mixed line endings

**Result**: Files are no longer marked as modified when opened. The unsaved indicator only appears after actual user edits.

## Impact

This fix eliminates a significant UI annoyance where users were constantly prompted about unsaved changes when they hadn't modified anything. Files are now only marked as modified when actual changes are made by the user.

### CODE REVIEW

**Comment by ffgan** [comment]
cc @Tkaixiang 

Some simple test feedback
I did a simple build on my Fedora. The current `trunk` branch does indeed cause the issue mentioned in this modification, and after switching to this PR, the problem was resolved. This fix should be effective.

File: src/main/filesystem/markdown.js [hunk 1]
```diff
@@ -108,33 +110,50 @@ export const loadMarkdownFile = async (
...
+    // but still convert to LF internally for the editor (required by MarkText)
+    if (lineEnding !== 'lf') {
+      adjustLineEndingOnSave = true
+      markdown = convertLineEndings(markdown, 'lf')
+    }
+    // When not auto-normalizing and trimTrailingNewline is set to auto-detect (2),
+    // we should use "disabled" (3) to preserve the file exactly as-is
+    if (trimTrailingNewline === 2) {
+      trimTrailingNewline = 3
+    }
```
Comment (Tkaixiang) [inline src/main/filesystem/markdown.js:152]: Consider not adjusting trimTrailingNewline here regardless of what the user sets. 

Since this setting is about automatic adjusting of line endings (CRLF/LF), it should not edit other preferences as well. Some users might want to trim trailing new lines but not line endings.

The default is also already set to Preserve, so it should not cause this modified msg by default

File: src/main/preferences/schema.json [hunk 2]
```diff
@@ -230,6 +230,11 @@
     "type": "boolean",
     "default": false
   },
+  "autoNormalizeMarkdownOnOpen": {
+    "description": "Editor--Automatically normalize line endings and detect trailing newline settings when opening files. When disabled, files are opened as-is and only normalized when saved.",
+    "type": "boolean",
+    "default": false
+  },
```
Comment (Tkaixiang) [inline src/main/preferences/schema.json:237]: You also need to add this in `renderer/src/store/preference.js` to actually specify default settings, this is only for searching

File: src/renderer/src/store/editor.js [hunk 3]
```diff
@@ -1036,6 +1036,12 @@ export const useEditorStore = defineStore('editor', {
         this.toc = listToTree(toc)
       }
 
+      // Ignore the first content change after file load (Muya normalizes content)
+      if (this.currentFile.isFirstContentChange) {
```
Comment (Tkaixiang) [inline src/renderer/src/store/editor.js:1040]: Consider not doing this since it silently suppreses file changes if there was no normalisation initially, instead, perhaps a notification could be sent if auto-normalisation of line endings/trailing new lines was carried out.

An alternative could be to modify the ground truth markdown directly instead of modifying the end lines through a change event

**Review by Tkaixiang — CHANGES_REQUESTED** [review]
Hey, thanks for this PR, just a few comments

**Comment by Tkaixiang** [comment]
Thanks for the PR, since I have extra time right now, I will be bringing this branch in for works

File: src/main/filesystem/markdown.js (hunk 1 above)
Comment (Tkaixiang) [reply src/main/filesystem/markdown.js:152]: Edit: I realised this option works more like an over-arching disabling of autoNormalisation for both line endings and trailing newlines, in that case, it will be useful to provide a useful visual hint in preferences for telling the user that trimming of trailing newlines is also disabled if you disable this

**Comment by Tkaixiang** [comment]
Upon further review, this PR does not fully solve the problem unfortunately, it was simply surpressing the first change which sometimes included normalisation. See my explanation in #31
